### ISSUE TITLE
pimping pythong script (adding input parameters)

### ISSUE THREAD

**Issue by NopeNix** [NopeNix/AI-Object-Counter#1]
# Description
the python script, as of right now, accepts only one Input parameter: an url. This should be changed, a a few more Parameters are needed which are described in the DoD Section of the Issue

# DoD
- [x] Script has an mandatory input Parameter "URL" which should use the current inpot argument
- [x] Script has an optional Parameter to Set Model (knowing that output of models are not standardized except for e.g. some from google)
- [x] Script has an mandatory input Parameter "Path" which should point to an image path instead of an URL
- [x] It should automatically be able to either use Path or URL up on which is specified. if none or two are specified then error
- [x] Short documentation how to use the new switches (can you do example pls? :) )

# Info:
It would be nice if i could run the script with somehting like this when the changes are implemented:
```bash
 python script.py -URL https://noporn.com/garden.jpeg -MODEL GOOGLEMODELBLA
```
right now i am running it like that:
```bash
 python script.py https://noporn.com/garden.jpeg
```

**Comment by AmateurAcademic** [comment]
I have made these changes, refactored the script a bit, and added in support for another model. I updated the README with info for this. Check out the refactor branch.
