### ISSUE TITLE
Add Additional Parameters to Python Script

### ISSUE THREAD

**Issue by NopeNix** [NopeNix/AI-Object-Counter#7]
right now the pyton script acceppts the following input parameters:

## `main.py` file
`python main.py --url image_url --model model_path`

## If possible i would like to be able to give the following additional input parameters:
`python main.py --url image_url --model model_path --include-picture-with-boundingboxes --filter "car","person"  --min-confidence 0,2`

### **--include-picture-with-boundingboxes** *(Switch | Optional Parameter)*
this parameter should add, to the existing json output:
```json
{
  ...
  "image-base64-encoded": "IMAGE BASE64 ENCODED HERE"
}

```

### **--filter** *(List of Strings | Optional Parameter)*
this parameter should filter the output, and what is displayed on the ```--include-picture-with-boundingboxes``` only the opjects specified should be displayed there can be multiple (e.g. "car","person")or just one or even none. the script should output everything what it detects when this parameter is not given

### **--confidence NUMBER** *(Integer | Optional Parameter)*
this parameter should filter the output, and what is displayed on the ```--include-picture-with-boundingboxes``` only objects with a given minimum confidence level between 0 and 1 (also e.g. 0,3 and so on) should be outputted in the JSON and on the ```--include-picture-with-boundingboxes```

**Comment by AmateurAcademic** [comment]
See `feature/bounding-boxes` branch. I updated the `README` to explain the additional optional args. It should be tested, the output base64 should be checked as an image to ensure it is correct, and additional changes to the other parts of the codebase that aren't python should be made.
